name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file pytorch/training/docker/2.3/py3/cu121/Dockerfile.gpu --tag py3-torch23-cu121:$(date +%s)
